openapi: 3
info:
  title: atsumare.info
  description: 'The internal api for atsumare info '
  contact:
    name: mirukushake
    url: 'http://github.com'
  version: 1
servers:
  - url: 'https://atsumareserver.run.goorm.io'
    description: remote dev
tags:
  - name: items
  - description: Physical/collectable items.
paths:
  /museum/bugs:
    get:
      summary: Get a list of bugs.
      tags:
        - items
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: get-bugs
      description: Bugs you can catch
      parameters:
        - schema:
            type: integer
          in: query
          name: locale
          required: true
        - schema:
            type: string
          in: query
          name: subtitle
    parameters: []
  /museum/fish:
    get:
      summary: Get a list of fish caught by rod.
      tags:
        - items
      responses: {}
      operationId: get-museum-fish
      description: Fish caught by rod
    parameters: []
  /museum/deep-sea-creatures:
    get:
      summary: Get
      tags:
        - items
      responses: {}
      operationId: get-museum-deep-sea-creatures
      parameters:
        - schema:
            type: string
          in: query
      description: Creatures caught in the ocean.
    parameters: []
